[advisories]
ignore = [
    "RUSTSEC-2020-0016", # `net2` unmaintained (need to update to Tokio 1.0)
    "RUSTSEC-2020-0036", # `failure` unmaintained (used by `cargo-edit`)
    "RUSTSEC-2020-0053", # `dirs` unmaintained (used by `cargo-edit`)
]

[output]
quiet = false
deny = ["warnings"]
